### ISSUE TITLE
Namespace ATT&CK IDs

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-frontend#113]
As a user, I want to be able to optionally namespace my ATT&CK IDs so that they won't conflict with ATT&CK or other organizations'. The namespace configuration should be part of the environment file.

Namespaced IDs have two parts, each optional:
- The ID range to generate IDs in. By default, ATT&CK uses 1000-2000 for IDs (e.g techniques start with T1000). Users should be able to specify any 4-digit number as their lower bound.
- the prefix for IDs. The ID prefix would be per organization, so were ATT&CK to add a prefix they would have IDs like `MITRE-T1000`. The prefix would be by the object _creator_, so modifiers of objects created by other organizations would not change the prefix. MITRE ATT&CK would not have a prefix since IDs won't be changing for ATT&CK, but other organizations would be encouraged to prefix their IDs.

See also #55.

**Comment by iguannalin** [comment]
* Note: there is a known edge case that can happen across the Workbench -- where one user can create a new StixObject at the same time a second user is creating a new one that is the same type, which would result in identical ATT&CK IDs being generated for both. This will not be addressed in this issue, as there is already 2 validations in place that are happening before a user saves a newly created StixObject--one occurs when the ATT&CK ID is automatically generated, and the other occurs after the user clicks the save button (during which if the id is non-unique/invalid it will not let the user proceed).
