### ISSUE TITLE
Parsing LinkByIDs

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-frontend#131]
As a user, I want to be able to add links from one object in the knowledge base to another. 

This should be done via LinkByID, which behaves rather like Citations. The LinkById marker, like a citation marker, references an index of the external_references array by `source_name`. The difference being that LinkByIds are visualized as a full hyperlink instead of a citation marker, and that LinkByIds do not get visualized up in the object's external references section.

When the user unfocuses the description field after editing, detect LinkByIds:
- If the LinkByID's object is found in the external_references already there is no further action required. 
- Otherwise, look up the object ID in the back-end and push the LinkById's corresponding reference to the external_references array.
   - `source_name` is the lookup used for the LinkById
   - `url` is the object's self-referential external reference URL (commonly stored in the first external reference of the object)
   - `description` is the object's `name`.
- If no object exists with that LinkByID, warn the user that the object cannot be found.

## Example
Raw STIX description:
``` 
After initial installation, (LinkById: S0565) runs a computation to delay execution.(Citation: Symantec RAINDROP January 2021)
```
object's external references
```json
"external_references": [
    {
        "source_name": "S0565",
        "url": "attack.mitre.org/software/S0565",
        "description": "Raindrop"
    }
    {
        "source_name": "Symantec RAINDROP January 2021",
        "url": "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/solarwinds-raindrop-malware",
        "description": "Symantec Threat Hunter Team. (2021, January 18). Raindrop: New Malware Discovered in SolarWinds Investigation. Retrieved January 19, 2021."
    },
]
```
Rendered description:
> After initial installation, [Raindrop](attack.mitre.org/software/S0565) runs a computation to delay execution.<sup>[[1]](https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/solarwinds-raindrop-malware)</sup>

**Comment by clemiller** [comment]
Superseded by #279
