### ISSUE TITLE
Make sure string values sent to the REST API are trimmed

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-frontend#187]
As a user of the application, I want it to make sure I don't accidentally include extra whitespace at the beginning or end of a value. This would help me avoid cases like naming a technique `"example technique "` by trimming it to `"example technique"`, and avoiding noncompliant URLs in external references.

Call the `trim()` method on serialization of string fields for all STIX objects.

**Comment by clemiller** [comment]
Resolved in #373
