### ISSUE TITLE
Add ability to add marking definitions to objects

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-frontend#188]
As a user, I want to be able to add marking definitions (e.g copyright statements) defined in my knowledge base to objects, and to view the marking definitions on objects in the knowledge base.

**Comment by isaisabel** [comment]
![Screen Shot 2021-06-30 at 10 50 33 AM](https://user-images.githubusercontent.com/28868888/123984392-9862da80-d992-11eb-9e07-87b6698692f6.png)

When hovered statements should display a list of non-TLP statements in a popover. When clicked, open a dialog to select the non-TLP marking defs to apply.

![Screen Shot 2021-06-30 at 10 58 50 AM](https://user-images.githubusercontent.com/28868888/123984403-9a2c9e00-d992-11eb-8255-5f99ceccc882.png)

May want to consider displaying the first few words of the statement instead of simply _{count} statements_ -- statement is not an intuitive term for users.

**Comment by IanDavila** [comment]
TLP and statements markings can only be modified in edit mode. If the object has statements or a TLP marking assigned to it then it will appear in the view mode.
