### ISSUE TITLE
Allow subtechnique-of relationships to be deprecated

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-frontend#219]
As a user, I want to be able to remove sub-techniques from a technique and vice versa.

Currently relationships of type `subtechnique-of` cannot be deprecated, and are therefore "permanent" once added. The user should be able to open the relationship-edit panel for` subtechnique-of`r elationships to deprecate or retarget them.

**Comment by ElJocko** [comment]
There is no requirement to retain an orphaned sub technique. Being able to deprecate the sub-technique itself or attach the sub-technique to a different parent technique covers the required use cases.  

Closed by #308
