### ISSUE TITLE
Got trouble when integrate with ATT&CK Navigator

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#230]
Hi I'm trying to integrate Workbench with Navigator, I changed the configration file `/src/assets/config.json` in Navigator server and the config looks like this.
```
{
    "versions": [
        {
            "name": "ATT&CK Workbench Data", 
            "domains": [
                {   
                    "name": "Enterprise", 
                    "data": ["http://localhost:3000/api/stix-bundles/?domain=enterprise-attack"]
                },
                {   
                    "name": "Mobile", 
                    "data": ["http://localhost:3000/api/stix-bundles/?domain=mobile-attack"]
                },
                {
                    "name": "ICS",
                    "data": ["http://localhost:3000/api/stix-bundles/?domain=ics-attack"]
                }
            ]
        }
    ]
} 
```
after this i clicked create new Layer in Navigator, i can see the config related to Workbench, but after i click create it just rolling and rolling without show any notice or result..
![image](https://user-images.githubusercontent.com/8390209/126296093-e5352fd1-65bf-4860-8e5a-8c709b54a47e.png)

Then I found an error through devtools. is there any knowns issue related to this?

![image](https://user-images.githubusercontent.com/8390209/126296310-5f487a1b-077e-448d-b14b-7ec4302327b4.png)

**Comment by isaisabel** [comment]
Hi @dickens88,

This is really more of an ATT&CK Navigator issue so I'm closing it in favor of tracking the fix in https://github.com/mitre-attack/attack-navigator/issues/324 (which is the same issue duplicated on that repo).
