### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by mayur-esh** [center-for-threat-informed-defense/attack-workbench-frontend#235]
Hello, I followed the "install and run" instructions mentioned in the Readme. However, this is the message I get post installation:

    docker-compose up
Starting attack-workbench-database ... done
Starting attack-workbench-rest-api ... done
Starting attack-workbench-collection-manager ... done
Starting attack-workbench-frontend           ... done
Attaching to attack-workbench-database, attack-workbench-rest-api, attack-workbench-collection-manager, attack-workbench-frontend
attack-workbench-database exited with code 132
attack-workbench-frontend | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
attack-workbench-frontend | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
attack-workbench-frontend | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
attack-workbench-frontend | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
attack-workbench-frontend | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
attack-workbench-frontend | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
attack-workbench-frontend | /docker-entrypoint.sh: Configuration complete; ready for start up
attack-workbench-collection-manager | 
attack-workbench-collection-manager | > attack-workbench-collection-manager@1.0.1 start /usr/src/app
attack-workbench-collection-manager | > node ./bin/www
attack-workbench-collection-manager | 
attack-workbench-rest-api | 
attack-workbench-rest-api | > attack-workbench-rest-api@1.0.1 start /usr/src/app
attack-workbench-rest-api | > node ./bin/www
attack-workbench-rest-api | 
attack-workbench-collection-manager | 2021-07-26T22:15:45.018Z [INFO] ** hostname = 41d241e88ca4
attack-workbench-collection-manager | 2021-07-26T22:15:45.022Z [INFO] ** type = Linux
attack-workbench-collection-manager | 2021-07-26T22:15:45.023Z [INFO] ** platform = linux
attack-workbench-collection-manager | 2021-07-26T22:15:45.023Z [INFO] ** arch = x64
attack-workbench-collection-manager | 2021-07-26T22:15:45.023Z [INFO] ** release = 5.4.0-80-generic
attack-workbench-collection-manager | 2021-07-26T22:15:45.024Z [INFO] ** uptime = 2819.43
attack-workbench-collection-manager | 2021-07-26T22:15:45.024Z [INFO] ** versions = {"node":"14.17.3","v8":"8.4.371.23-node.67","uv":"1.41.0","zlib":"1.2.11","brotli":"1.0.9","ares":"1.17.1","modules":"83","nghttp2":"1.42.0","napi":"8","llhttp":"2.1.3","openssl":"1.1.1k","cldr":"39.0","icu":"69.1","tz":"2021a","unicode":"13.0"}
attack-workbench-collection-manager | 2021-07-26T22:15:45.050Z [INFO] ATT&CK Workbench Collection Manager app starting
attack-workbench-collection-manager | 2021-07-26T22:15:45.050Z [INFO] Configuring the app
attack-workbench-collection-manager | 2021-07-26T22:15:45.189Z [INFO] Starting express
attack-workbench-rest-api | 2021-07-26T22:15:45.392Z [INFO] ** hostname = 37d9a5aa6315
attack-workbench-rest-api | 2021-07-26T22:15:45.397Z [INFO] ** type = Linux
attack-workbench-rest-api | 2021-07-26T22:15:45.398Z [INFO] ** platform = linux
attack-workbench-rest-api | 2021-07-26T22:15:45.399Z [INFO] ** arch = x64
attack-workbench-rest-api | 2021-07-26T22:15:45.400Z [INFO] ** release = 5.4.0-80-generic
attack-workbench-rest-api | 2021-07-26T22:15:45.401Z [INFO] ** uptime = 2819.81
attack-workbench-rest-api | 2021-07-26T22:15:45.401Z [INFO] ** versions = {"node":"14.17.3","v8":"8.4.371.23-node.67","uv":"1.41.0","zlib":"1.2.11","brotli":"1.0.9","ares":"1.17.1","modules":"83","nghttp2":"1.42.0","napi":"8","llhttp":"2.1.3","openssl":"1.1.1k","cldr":"39.0","icu":"69.1","tz":"2021a","unicode":"13.0"}
attack-workbench-rest-api | 2021-07-26T22:15:45.402Z [INFO] Setting up the database connection
attack-workbench-collection-manager | 2021-07-26T22:15:45.715Z [INFO] CORS is enabled
attack-workbench-collection-manager | 2021-07-26T22:15:45.799Z [INFO] Enabling HTTP request logging
attack-workbench-collection-manager | 2021-07-26T22:15:46.200Z [INFO] Creating the routes
attack-workbench-collection-manager | 2021-07-26T22:15:47.035Z [INFO] Starting the scheduler
attack-workbench-collection-manager | 2021-07-26T22:15:47.037Z [INFO] Starting the REST server
attack-workbench-collection-manager | 2021-07-26T22:15:47.300Z [INFO] Listening at http://:::3001
attack-workbench-collection-manager | 2021-07-26T22:15:47.300Z [INFO] ATT&CK Workbench Collection Manager start up complete
attack-workbench-rest-api | 2021-07-26T22:15:47.342Z [INFO] Mongoose attempting to connect to mongodb://attack-workbench-database/attack-workspace
attack-workbench-collection-manager | 2021-07-26T22:15:57.038Z [INFO] Scheduler running...
attack-workbench-rest-api | 2021-07-26T22:15:47.342Z [INFO] Mongoose attempting to connect to mongodb://attack-workbench-database/attack-workspace
attack-workbench-collection-manager | 2021-07-26T22:15:57.038Z [INFO] Scheduler running...
attack-workbench-collection-manager | 2021-07-26T22:15:57.068Z [ERROR] Unable to get existing collection indexes: Error: Connection refused
attack-workbench-collection-manager | 2021-07-26T22:16:07.049Z [INFO] Scheduler running...
attack-workbench-collection-manager | 2021-07-26T22:16:07.053Z [ERROR] Unable to get existing collection indexes: Error: Connection refused
attack-workbench-collection-manager | 2021-07-26T22:16:17.060Z [INFO] Scheduler running...
attack-workbench-collection-manager | 2021-07-26T22:16:17.063Z [ERROR] Unable to get existing collection indexes: Error: Connection refused
attack-workbench-rest-api | 2021-07-26T22:16:17.381Z [ERROR] Mongoose connection error: MongooseServerSelectionError: getaddrinfo ENOTFOUND attack-workbench-database
attack-workbench-rest-api | 2021-07-26T22:16:17.381Z [ERROR] Database (mongoose) connection is required. Terminating app.
attack-workbench-rest-api | npm ERR! code ELIFECYCLE
attack-workbench-rest-api | npm ERR! errno 1
attack-workbench-rest-api | npm ERR! attack-workbench-rest-api@1.0.1 start: `node ./bin/www`
attack-workbench-rest-api | npm ERR! Exit status 1
attack-workbench-rest-api | npm ERR! 
attack-workbench-rest-api | npm ERR! Failed at the attack-workbench-rest-api@1.0.1 start script.
attack-workbench-rest-api | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
attack-workbench-rest-api | 
attack-workbench-rest-api | npm ERR! A complete log of this run can be found in:
attack-workbench-rest-api | npm ERR!     /root/.npm/_logs/2021-07-26T22_16_17_411Z-debug.log
attack-workbench-rest-api exited with code 1
attack-workbench-collection-manager | 2021-07-26T22:16:27.070Z [INFO] Scheduler running...
attack-workbench-collection-manager | 2021-07-26T22:16:27.079Z [ERROR] Unable to get existing collection indexes: Error: Host not found
attack-workbench-collection-manager | 2021-07-26T22:16:37.081Z [INFO] Scheduler running...
attack-workbench-collection-manager | 2021-07-26T22:16:37.088Z [ERROR] Unable to get existing collection indexes: Error: Host not found
    
Can some one help me solve this issue?

**Comment by isaisabel** [comment]
Hi @mayur-esh,

It looks like the mongo docker container crashed, and since the REST API container is dependent on it it exited as well.

>  attack-workbench-database exited with code 132
> [...]
>  attack-workbench-rest-api | 2021-07-26T22:16:17.381Z [ERROR] Mongoose connection error: MongooseServerSelectionError: getaddrinfo ENOTFOUND attack-workbench-database
> [...]
> attack-workbench-rest-api exited with code 1

We don't actually maintain the `mongo` docker image ourselves, rather we use the official image [here](https://hub.docker.com/_/mongo). 

What OS are you running on? It looks like newer mongo versions [may have compatibility issues with Ubuntu when run on older CPUs](https://github.com/docker-library/mongo/issues/485).

Try changing [this line](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docker-compose.yml#L34) to the following to roll-back to an older version of the mongo image:

```
    image: mongo:4.4.6
```

And then run the docker-compose instructions again.

**Comment by mayur-esh** [comment]
Ah! That solved the issue. Thanks @isaisabel !
