### ISSUE TITLE
Proper Installation for full Workbench

### ISSUE THREAD

**Issue by shrishtijain** [center-for-threat-informed-defense/attack-workbench-frontend#236]
Hi all, 

Can anyone please help me with the proper installation of full workbench, specially following issues.
**Rest Api**- How to set environmental variables and configuration settings , as if I give no as explained in document is show error and also same for **collection manager**.

Please help me in making my project up and running.

Thanks in advance.

**Comment by isaisabel** [comment]
Hi @shrishtijain,

If you are on Linux or macOS you can use `export` to add an environment variable. For the REST API the only required environment variable is DATABASE_URL (which should point to your local MongoDB instance). For me the startup of the REST API looks like this:

```bash
# set up the environment
export DATABASE_URL=mongodb://localhost/attack-workspace
# run the REST API
node bin/www
```

The Collection Manager does not require any environment variables be set for the default install, but if you wanted to change the environment you can use the `export` command like demonstrated above.

For Windows [I believe you would use `set`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) in the place of `export`, but unfortunately I don't have a windows computer to test on.

You may want to consider using the [docker install instructions](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/docker-compose.md) which are simpler and avoid the need to set the environment variables yourself.
