### ISSUE TITLE
Typo in  attack-workbench-frontend/docs/collections.md 

### ISSUE THREAD

**Issue by swartik** [center-for-threat-informed-defense/attack-workbench-frontend#237]
In the Object Version Reference Properties section, the description for `object_modified` has the sentence:

     It MUST be an exact for the modified time of the STIX object being referenced.

There's a missing word between "exact" and "for".

**Comment by isaisabel** [comment]
Hi @swartik,

Thank you for reaching out! [I've fixed this on the develop branch](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/develop/docs/collections.md#object-version-reference-properties) and the next release will move that to master.

For what it's worth, the text of that field is mostly identical to the corresponding field on STIX 2.1's [language content](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_z9r1cwtu8jja) SDO.

**Comment by swartik** [comment]
@isaisabel, I hadn't known about the relationship to STIX. Thanks very much.

**Comment by isaisabel** [comment]
The data imported and exported from Workbench is an extension of STIX 2.1. You can read more about the data model here if you're interested: https://github.com/mitre-attack/attack-stix-data/blob/master/USAGE.md
