### ISSUE TITLE
Sync color theme with OS settings

### ISSUE THREAD

**Issue by isaisabel** [center-for-threat-informed-defense/attack-workbench-frontend#242]
As a user of ATT&CK Workbench, I want to be able to optionally configure the UI's color theme to automatically sync with OS settings through the use of [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

This should be marked as an alternative to setting the theme directly so that users can override the OS theme if desired. See Slack's color theme selection for example:

![image](https://user-images.githubusercontent.com/28868888/132342037-4888be13-0119-4ecc-a1e7-21ba60de1c56.png)

**Comment by isaisabel** [comment]
See also https://github.com/mitre-attack/attack-navigator/issues/71

**Comment by isaisabel** [comment]
The following SCSS functions should be able to augment/replace the current color system with support for OS color theme syncing:
```scss
/// assign the property with different values in the light and dark themes
/// @param {property} $property the property you want to set the value of
/// @param {value} $light-value the value to assign when in the light theme
/// @param {value} $dark-value the value to assign when in the dark theme
@mixin adaptive-color($property, $light-value, $dark-value) {
    @include adaptive-color-light-only($property, $light-value);
    @include adaptive-color-dark-only($property, $dark-value);
}

/// assign the property with the given value only when in the light theme
/// @param {property} $property the property you want to set the value of
/// @param {value} $light-value the value to assign when in the light theme
@mixin adaptive-color-light-only($property, $light-value) {
    .theme-use-system & { 
        // when the ancestor class shows that the app is configured to use the system theme,
        // use a media query to assign the light value
        @media (prefers-color-scheme: light) { #{$property}: $light-value; }
    }
    .theme-override-light & {
        // when the ancestor class shows that the app is configured to use the light theme,
        // assign the light value
        #{$property}: $light-value;
    }
}

/// assign the property with the given value only when in the dark theme
/// @param {property} $property the property you want to set the value of
/// @param {value} $light-value the value to assign when in the light theme
/// @param {value} $dark-value the value to assign when in the dark theme
@mixin adaptive-color-dark-only($property, $dark-value) {
    .theme-use-system & { 
        // when the ancestor class shows that the app is configured to use the system theme,
        // use a media query to assign the dark value
        @media (prefers-color-scheme: dark) { #{$property}: $dark-value; }
    }
    .theme-override-dark & {
        // when the ancestor class shows that the app is configured to use the dark theme,
        // assign the dark value
        #{$property}: $dark-value;
    }
}
```
Note that currently the theme is conveyed using `.dark` and `.light` [added to the app-root](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/app/src/app/app.component.html#L1). The above functions assume that this will be replaced by `.theme-override-light` for light theme, `.theme-override-dark` for dark theme, and `.theme-use-system` to sync with the OS configuration.

**Comment by seansica** [comment]
@clemiller The feature branch I added for this issue, [242-sync-color-theme-with-os-settings](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/tree/242-sync-color-theme-with-os-settings), doesn't directly address or incorporate the CSS changes mentioned above. But it does modify the theme behavior by adjusting the way that `theme` is set when the app component is initialized.

When the user initially opens Workbench, the theme will be set based on the user's OS/browser settings, rather than always setting it to light mode.

Before, the theme was being initialized to light:
```
public theme = "light";
```

Now/instead, it is being set when the `ngOnInit` lifecycle hook is called:
```
public theme;

/**
 * Sets the initial/default theme based on the operating system/browser settings. Called by ngOnInit.
 */
public setDefaultTheme(): void {
    // The theme property will be set to 'dark' if the operating system or browser is in dark mode, and 'light' if
    // it is in light mode
    const mediaQueryList = window.matchMedia('(prefers-color-scheme: dark)');
    this.theme = mediaQueryList.matches ? Theme.DarkMode : Theme.LightMode;

    // use the addEventListener method of the MediaQueryList object to set up a listener that will be called
    // whenever the light/dark mode setting changes
    mediaQueryList.addEventListener('change', (event) => {
      this.theme = event.matches ? Theme.DarkMode : Theme.LightMode;
    });
}

ngOnInit(): void {
  this.setDefaultTheme();
}
```

All string instances of "light" and "dark" were also replaced with const refs:
e.g.,
Before:
```
this.theme = event.matches ? "dark" : "light";
```

After:
```
this.theme = event.matches ? Theme.DarkMode : Theme.LightMode;
```

`app/globals.ts`:
```
export const Theme = {
  LightMode: 'light',
  DarkMode: 'dark'
};
```

If this looks agreeable to you, I will open a PR - let me know!

**Comment by clemiller** [comment]
@seansica your approach LGTM. Please go ahead and open a PR for this. Thanks!
