### ISSUE TITLE
Display entities mentioned by a reference/article

### ISSUE THREAD

**Issue by burritoblue** [center-for-threat-informed-defense/attack-workbench-frontend#263]
As a user of the Workbench, I want to be able to select a reference (article, report, etc) and display all entities (techniques/groups/software) mentioned within/by that reference.

**Comment by isaisabel** [comment]
Hi @burritoblue,

Thank you for opening this issue! I'm not sure we can easily infer from the content of a reference what techniques are relevant -- that's more of a thing for [tram](https://github.com/center-for-threat-informed-defense/tram/), which may be integrated into Workbench eventually (#14).

However, we could definitely show which objects in the local knowledge base _cite_ a given reference. This is already done behind the scenes (if you edit a reference in the sidebar, it edits the copy on all the objects in the knowledge base using the reference). So it wouldn't be too hard to add in that way.

**Comment by burritoblue** [comment]
Hi @isaisabel that is exactly what I meant: a way to pivot to a reference and see what is statically mapped to it (after the analyst has done all the work to create the relationships of course).

**Comment by clemiller** [comment]
Changes have been staged on `develop` and will be included in the upcoming release.
