### ISSUE TITLE
User Login and Logout

### ISSUE THREAD

**Issue by clemiller** [center-for-threat-informed-defense/attack-workbench-frontend#266]
As a User of ATT&CK Workbench, I want to be able to log in to or log out of the application.
- Prior to login, I should only have access to the home page.
- Once logged in, I should see my identity icon in the header and have the option to logout.

**Comment by isaisabel** [comment]
I think unauthenticated users may also want to access the documentation pages:
- An individual stumbling upon the application deployed within their organization without knowing what it is may want to refer to that documentation to determine if they want to register
- Said documentation may also include registration instructions.

Given that the documentation pages on Workbench simply mirror the `docs/` folder of this repository, there shouldn't be any security risk to providing access to those pages to unauthenticated users.
