### ISSUE TITLE
can't integrate all data type with Navigator

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#272]
Hi,

I'm trying to integrate workbench with attack-navigator 4.5.4, It seems some of the data types in workbench can not be shown in Navigator correctly. 

I built workbench with the latest code in master branch. I created technique, mitigation, group, software, datasource one for each in workbench. after a while, i tried to find them in Navigator(The Navigator should sync all the new items i created in workbench as i understand). But `group` and `datasource` can not be found there (technique, mitigation, software are synchronized correctly)

I suppose maybe some errors happened when handling `group` and `datasource`. 

BTW, i also integate with `attack-website`, website works fine with all the items above...

**Comment by clemiller** [comment]
Closing; this issue was addressed in [navigator#397](https://github.com/mitre-attack/attack-navigator/issues/397).
