### ISSUE TITLE
The user-defined Mitigation object sync from Workbench can't be shown correctly under Techniques

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#284]
Hi ,

I created [this issue](https://github.com/mitre-attack/attack-website/issues/356) for Website but i think maybe the root cause may related to Workbench. Please check, thank you very much.

**Comment by IanDavila** [comment]
Closing as it pertains to the Website build instead (https://github.com/mitre-attack/attack-website/issues/358). Thanks for reporting once again @dickens88.
