### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by Aldo-2077** [center-for-threat-informed-defense/attack-workbench-frontend#354]
Hello.  
I'm running Ubuntu LTS 20.04.
I have followed the Docker Installation Instructions and at step 2 Build Docker Images, I used the command "docker compose up".
The install just keeps running and running.  It's been over 2 hours.
Is it supposed to take this long?  Any help is appreciated.

I'm taking the Extending ATT&CK with ATT&CK Workbench course.  The instructor said it should only take about 10 minutes.
This is what is running over and over on my screen, except the snapshot number keeps increasing:

attack-workbench-database            | {"t":{"$date":"2022-05-17T00:40:58.486+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":"[1652748058:486456][1:0x7f80eb55b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 103, snapshot max: 103 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 446"}}
attack-workbench-collection-manager  | 2022-05-17T00:41:01.756Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-05-17T00:41:01.763Z [HTTP] GET /api/collection-indexes 200 3.491 ms - 2
attack-workbench-collection-manager  | 2022-05-17T00:41:11.766Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-05-17T00:41:11.771Z [HTTP] GET /api/collection-indexes 200 2.014 ms - 2
attack-workbench-collection-manager  | 2022-05-17T00:41:21.776Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-05-17T00:41:21.781Z [HTTP] GET /api/collection-indexes 200 2.024 ms - 2
attack-workbench-collection-manager  | 2022-05-17T00:41:31.785Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-05-17T00:41:31.818Z [HTTP] GET /api/collection-indexes 200 28.762 ms - 2
attack-workbench-collection-manager  | 2022-05-17T00:41:41.795Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-05-17T00:41:41.801Z [HTTP] GET /api/collection-indexes 200 2.829 ms - 2
attack-workbench-collection-manager  | 2022-05-17T00:41:51.806Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-05-17T00:41:51.810Z [HTTP] GET /api/collection-indexes 200 2.479 ms - 2

**Comment by ElJocko** [comment]
Hi - It looks like the installation was successful. When you run the command...

```
docker compose up
```

...Docker will start the services and then stream the log output to your terminal. Most of what you're seeing there is the output from Collection Manager as it periodically checks with the REST API to retrieve the current collection indexes. That's a normal background process for Workbench.

You might want to add the `-d` flag to your startup command:

```
docker compose up -d
```

This starts the services, but then detaches your terminal from the logs. You can check to see that the services are running with this command:
```
docker container ls
```
And you can still view logging output if necessary, using a command like:
```
docker logs --since 1h attack-workbench-rest-api
```
This will display all logs from the rest-api service from the last hour.

**Comment by Aldo-2077** [comment]
Thank you for the quick response.  This worked just as you described.
