### ISSUE TITLE
Missing the CSS class for the Overlay Container when using the Browser default light/dark mode

### ISSUE THREAD

**Issue by ElJocko** [center-for-threat-informed-defense/attack-workbench-frontend#436]
This error occurs if the user hasn't set the light/dark theme using the 'toggle theme' button.

- The code gets the browser default theme from the browser and sets the theme, but it doesn't update the overlay container's classes
- Since the overlay container doesn't get the 'light' or 'dark' class added, the dialog box doesn't pick up the correct style and the background isn't set correctly

![image](https://user-images.githubusercontent.com/2816779/214890659-0cc1e906-61b9-40e3-878f-3135505e19a8.png)

**Comment by clemiller** [comment]
Changes staged on develop.
