### ISSUE TITLE
Bug: unable to docker-compose

### ISSUE THREAD

**Issue by mbrg** [center-for-threat-informed-defense/attack-workbench-frontend#440]
Hi there,
I'm trying to set up the workbench app for the first time by following [this guide](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/docker-compose.md).

When running the `docker-compose up` I get the following error:

```bash
user@machine:~/attack-workbench/attack-workbench-frontend$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I'm on Ubuntu 20.04 running on WSL. More info:
```bash
user@machine:~/attack-workbench/attack-workbench-frontend$ docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by seansica** [comment]
According to your output, it appears that your compose client is version 1.25.0.

According to the [release notes for docker compose 1.25.0](https://github.com/docker/compose/releases/tag/1.25.0), the maximum supported Compose file format is 3.7. 

The Compose template provided in this repository is 3.9. You will need to upgrade your compose client to one that supports 3.9.

**Comment by mbrg** [comment]
> According to your output, it appears that your compose client is version 1.25.0.
> 
> According to the [release notes for docker compose 1.25.0](https://github.com/docker/compose/releases/tag/1.25.0), the maximum supported Compose file format is 3.7.
> 
> The Compose template provided in this repository is 3.9. You will need to upgrade your compose client to one that supports 3.9.

Thank you
