### ISSUE TITLE
Duplicate Entries in some Dropdown Lists

### ISSUE THREAD

**Issue by ElJocko** [center-for-threat-informed-defense/attack-workbench-frontend#454]
Dropdown lists that are populated from domain-specific allowed values show duplicate entries when the domains have overlapping allowed values. This applies to Data Sources (collection layers and platforms) and Software (platforms) and maybe other places??

For example, in the list of allowed values for Software `x_mitre_platforms`, Enterprise and ICS both allow the value "Windows". In Workbench, when creating a new Software object, if the domain is set to both Enterprise and ICS, the Platforms dropdown displays "Windows" twice. It also exhibits some odd behavior (e.g., clicking on the second "Windows" entry results in the first "Windows" entry being selected).

**Comment by clemiller** [comment]
Changes are staged on `develop` and will be included in the next release.
