### ISSUE TITLE
[REQUEST] Create new Domains, components, etc. 

### ISSUE THREAD

**Issue by darksheer** [center-for-threat-informed-defense/attack-workbench-frontend#523]
**Is your feature request related to a problem? Please describe.**
Unable to edit DOMAINS -- i.e. Create brand new Matrix's, components, etc. 

**Describe the solution you'd like**
I'm wanting to create a new domain -- not to utilize the existing enterprise-attack, ics-attack, etc.  The current version of Workbench doesn't allow for creating new domains, components, etc. 

**Describe alternatives you've considered**
I've attempted following this guide, to edit the existing enterprise-attack domain, after deleting the volumes and restarting the containers, I'm able to select the new domain.  However, the linked Techniques to the Tactics are not displayed.

VIEW -> MATRICES -> MATRIX. 

https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/336

Any guidance would be greatly appreciated.

**Comment by clemiller** [comment]
Hi @darksheer,

Thanks for opening up this issue. This appears to be the same content request as #38 (see also #35 and #36). I am closing it as a duplicate, but feel free to re-open if there's additional functionality you're looking for that isn't covered in the other issues.

**Comment by darksheer** [comment]
I guess this begs the broader question -- is the broader MITRE ATT&CK community looking for collaboration in such way that enabled the creation of new frameworks?  Based on the tooling, it doesn't appear that way.
