### ISSUE TITLE
Security Question: Telemetry/Analytics/Connections to Third Parties

### ISSUE THREAD

**Issue by rainmana** [center-for-threat-informed-defense/attack-workbench-frontend#525]
Hi MITRE Engenuity/Workbench Team!

I'm interested in using MITRE ATT&CK Workbench (Frontend, REST API, Database, etc.) in my environment, but I'm concerned about any type of telemetry being sent to MITRE itself, a third party, etc. for OpSec reasons. Is it possible to get something added to the documentation that indicates whether or not this is done? I've gone over the docs pretty extensively, but it's still possible I may have missed docs that may have covered this.

Also, do you happen to do regular scans of the application and its components to ensure the application isn't vulnerable? And if so, is it possible for your team to publish this to the GitHub repositories?

Thanks!

Alec

**Comment by ElJocko** [comment]
Hi rainmana!

ATT&CK Workbench doesn't collect or send any telemetry data to MITRE or any other entity. That seems like something that we can add to our documentation to make it clear.

In terms of vulnerabilities, we use static scans of the code to identify dependencies that have known vulnerabilities and address those when we encounter them. We haven't performed any pen testing or similar exercises though.

**Comment by rainmana** [comment]
Thank you so much for the clarity/added context! It helps a lot with the selection process for a tool like this! If you end up adding static scan results and/or clarity about the presence of telemetry, I'd love a link, but no worries if not!

Thanks again for the fast response time in answering too!

Alec (Rainmana)
